language: go
go:
- 1.13.x
- 1.14.x
- 1.15.x
- 1.16.x
dist: focal
install:
- go get -u golang.org/x/lint/golint
script:
- golint -set_exit_status ./...
- go fmt ./...
- # fail if go fmt changed anything
- git status --porcelain
- test "$(git status --porcelain)"
- go build
- go test ./...
